name: CI-CD

on:

  push:
    branches: [ main ]
    
  pull_request:
  
    branches: [ main ]
 
  workflow_dispatch:

jobs:
  
  CI:
    
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Docker Login
        uses: docker/login-action@v1.10.0
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PWD }}
      - name: Docker Build and Push
        uses: docker/build-push-action@v2.7.0
        with:
          context: conversao-temperatura/src
          file: conversao-temperatura/src/Dockerfile
          push: true
          tags: |
            wwrmaia/conversao-temperatura:latest
            wwrmaia/conversao-temperatura:${{github.run_number}}
  
  CD:    
    needs: [CI]
    runs-on: ubuntu-tatest
    
    steps:
      - uses: actions/checkout@v2
      - name: Kubernetes set context
        uses: Azure/k8s-set-context@v1.1
        with:
          method: kuberconfig
          kuberconfig: ${{ secrets.K8S_KUBECONFIG }}
          
      - uses: Azure/k8s-deploy@v1.3
        with:
          images: wwrmaia/conversao-temperatura:${{github.run_number}}
          manifests: |
            k8s/meudeployment.yaml
